name: dispatch receiver

on:
  repository_dispatch:
    types:
      - power-apps

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dispatch trigger
      #if: github.event.action == "YOUR_EVENT_TYPE"
      run: |
        echo "repository_dispatch triggered"
    - run: echo ${{ github.event.client_payload.sha }}
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - name: print whole context
      env:
        GITHUB_CONTEXT:  ${{ toJson(github) }} 
        VARS_CONTEXT:  ${{ toJson(vars) }} 
      run: |
        echo "GITHUB_CONTEXT is $GITHUB_CONTEXT"
        echo "VARS_CONTEXT is $VARS_CONTEXT"
        echo "event is  ${{ GITHUB_CONTEXT.event }} "

