name: dispatch receiver

on:
  repository_dispatch:
    types:
      - power-apps

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dispatch trigger
      #if: github.event.action == "YOUR_EVENT_TYPE"
      run: |
        echo "repository_dispatch triggered"
    - run: echo ${{ github.event.client_payload.sha }}
    - run: echo ${{ github.event.client_payload }}
